-- Generated by scripts/generate_migration_od_clean_sql.py.
-- Do not edit generated age bucket expressions by hand.

BEGIN;

CREATE SCHEMA IF NOT EXISTS clean;

CREATE TABLE IF NOT EXISTS clean.clean_inflow (
    date integer NOT NULL,
    region_sido text NOT NULL,
    region_sigungu text NOT NULL,
    from_sido text NOT NULL,
    from_sigungu text NOT NULL,
    inflow bigint NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS clean_inflow_key
    ON clean.clean_inflow (
        date,
        region_sido,
        region_sigungu,
        from_sido,
        from_sigungu
    );

CREATE TABLE IF NOT EXISTS clean.clean_inflow_sex (
    date integer NOT NULL,
    region_sido text NOT NULL,
    region_sigungu text NOT NULL,
    from_sido text NOT NULL,
    from_sigungu text NOT NULL,
    sex text NOT NULL,
    inflow bigint NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS clean_inflow_sex_key
    ON clean.clean_inflow_sex (
        date,
        region_sido,
        region_sigungu,
        from_sido,
        from_sigungu,
        sex
    );

CREATE TABLE IF NOT EXISTS clean.clean_inflow_age (
    date integer NOT NULL,
    region_sido text NOT NULL,
    region_sigungu text NOT NULL,
    from_sido text NOT NULL,
    from_sigungu text NOT NULL,
    age text NOT NULL,
    inflow bigint NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS clean_inflow_age_key
    ON clean.clean_inflow_age (
        date,
        region_sido,
        region_sigungu,
        from_sido,
        from_sigungu,
        age
    );

CREATE TABLE IF NOT EXISTS clean.clean_inflow_sex_age (
    date integer NOT NULL,
    region_sido text NOT NULL,
    region_sigungu text NOT NULL,
    from_sido text NOT NULL,
    from_sigungu text NOT NULL,
    sex text NOT NULL,
    age text NOT NULL,
    inflow bigint NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS clean_inflow_sex_age_key
    ON clean.clean_inflow_sex_age (
        date,
        region_sido,
        region_sigungu,
        from_sido,
        from_sigungu,
        sex,
        age
    );

CREATE TABLE IF NOT EXISTS clean.clean_outflow (
    date integer NOT NULL,
    region_sido text NOT NULL,
    region_sigungu text NOT NULL,
    to_sido text NOT NULL,
    to_sigungu text NOT NULL,
    outflow bigint NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS clean_outflow_key
    ON clean.clean_outflow (
        date,
        region_sido,
        region_sigungu,
        to_sido,
        to_sigungu
    );

CREATE TABLE IF NOT EXISTS clean.clean_outflow_sex (
    date integer NOT NULL,
    region_sido text NOT NULL,
    region_sigungu text NOT NULL,
    to_sido text NOT NULL,
    to_sigungu text NOT NULL,
    sex text NOT NULL,
    outflow bigint NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS clean_outflow_sex_key
    ON clean.clean_outflow_sex (
        date,
        region_sido,
        region_sigungu,
        to_sido,
        to_sigungu,
        sex
    );

CREATE TABLE IF NOT EXISTS clean.clean_outflow_age (
    date integer NOT NULL,
    region_sido text NOT NULL,
    region_sigungu text NOT NULL,
    to_sido text NOT NULL,
    to_sigungu text NOT NULL,
    age text NOT NULL,
    outflow bigint NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS clean_outflow_age_key
    ON clean.clean_outflow_age (
        date,
        region_sido,
        region_sigungu,
        to_sido,
        to_sigungu,
        age
    );

CREATE TABLE IF NOT EXISTS clean.clean_outflow_sex_age (
    date integer NOT NULL,
    region_sido text NOT NULL,
    region_sigungu text NOT NULL,
    to_sido text NOT NULL,
    to_sigungu text NOT NULL,
    sex text NOT NULL,
    age text NOT NULL,
    outflow bigint NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS clean_outflow_sex_age_key
    ON clean.clean_outflow_sex_age (
        date,
        region_sido,
        region_sigungu,
        to_sido,
        to_sigungu,
        sex,
        age
    );

CREATE INDEX IF NOT EXISTS migration_od_statsym_idx
    ON raw.migration_od ("statsYm");

CREATE TEMP TABLE IF NOT EXISTS clean_migration_od_requested_dates (
    date integer PRIMARY KEY
) ON COMMIT PRESERVE ROWS;

CREATE TEMP TABLE clean_migration_od_missing_dates ON COMMIT DROP AS
SELECT DISTINCT raw_mo."statsYm"::integer AS date
FROM raw.migration_od AS raw_mo
JOIN clean_migration_od_requested_dates AS requested
  ON raw_mo."statsYm" = requested.date::text
UNION
SELECT DISTINCT raw_mo."statsYm"::integer AS date
FROM raw.migration_od AS raw_mo
WHERE NOT EXISTS (
    SELECT 1
    FROM clean_migration_od_requested_dates
)
  AND (
      NOT EXISTS (
          SELECT 1
          FROM clean.clean_inflow AS existing
          WHERE existing.date = raw_mo."statsYm"::integer
      )
      OR NOT EXISTS (
          SELECT 1
          FROM clean.clean_inflow_sex AS existing
          WHERE existing.date = raw_mo."statsYm"::integer
      )
      OR NOT EXISTS (
          SELECT 1
          FROM clean.clean_inflow_age AS existing
          WHERE existing.date = raw_mo."statsYm"::integer
      )
      OR NOT EXISTS (
          SELECT 1
          FROM clean.clean_inflow_sex_age AS existing
          WHERE existing.date = raw_mo."statsYm"::integer
      )
      OR NOT EXISTS (
          SELECT 1
          FROM clean.clean_outflow AS existing
          WHERE existing.date = raw_mo."statsYm"::integer
      )
      OR NOT EXISTS (
          SELECT 1
          FROM clean.clean_outflow_sex AS existing
          WHERE existing.date = raw_mo."statsYm"::integer
      )
      OR NOT EXISTS (
          SELECT 1
          FROM clean.clean_outflow_age AS existing
          WHERE existing.date = raw_mo."statsYm"::integer
      )
      OR NOT EXISTS (
          SELECT 1
          FROM clean.clean_outflow_sex_age AS existing
          WHERE existing.date = raw_mo."statsYm"::integer
      )
  );

DELETE FROM clean.clean_inflow
WHERE date IN (SELECT date FROM clean_migration_od_missing_dates);

DELETE FROM clean.clean_inflow_sex
WHERE date IN (SELECT date FROM clean_migration_od_missing_dates);

DELETE FROM clean.clean_inflow_age
WHERE date IN (SELECT date FROM clean_migration_od_missing_dates);

DELETE FROM clean.clean_inflow_sex_age
WHERE date IN (SELECT date FROM clean_migration_od_missing_dates);

DELETE FROM clean.clean_outflow
WHERE date IN (SELECT date FROM clean_migration_od_missing_dates);

DELETE FROM clean.clean_outflow_sex
WHERE date IN (SELECT date FROM clean_migration_od_missing_dates);

DELETE FROM clean.clean_outflow_age
WHERE date IN (SELECT date FROM clean_migration_od_missing_dates);

DELETE FROM clean.clean_outflow_sex_age
WHERE date IN (SELECT date FROM clean_migration_od_missing_dates);

CREATE TEMP TABLE migration_od_standardized ON COMMIT DROP AS
WITH
sido_by_name(raw_sido, region_sido) AS (
    VALUES
        ('서울특별시', '서울'),
        ('부산광역시', '부산'),
        ('대구광역시', '대구'),
        ('인천광역시', '인천'),
        ('광주광역시', '광주'),
        ('대전광역시', '대전'),
        ('울산광역시', '울산'),
        ('세종특별자치시', '세종'),
        ('경기도', '경기'),
        ('강원도', '강원'),
        ('강원특별자치도', '강원'),
        ('충청북도', '충북'),
        ('충청남도', '충남'),
        ('전라북도', '전북'),
        ('전북특별자치도', '전북'),
        ('전라남도', '전남'),
        ('경상북도', '경북'),
        ('경상남도', '경남'),
        ('제주특별자치도', '제주')
),
prepared AS (
    SELECT
        raw_mo."statsYm"::integer AS date,
        btrim(raw_mo."mvinAdmmCd") AS destination_code,
        btrim(raw_mo."mvinCtpvNm") AS destination_sido_raw,
        btrim(raw_mo."mvinSggNm") AS destination_sigungu_raw,
        btrim(raw_mo."mvtAdmmCd") AS origin_code,
        btrim(raw_mo."mvtCtpvNm") AS origin_sido_raw,
        btrim(raw_mo."mvtSggNm") AS origin_sigungu_raw,
        coalesce(nullif(regexp_replace(raw_mo."totNmprCnt", '[^0-9-]', '', 'g'), ''), '0')::bigint AS total_count,
        coalesce(nullif(regexp_replace(raw_mo."maleNmprCnt", '[^0-9-]', '', 'g'), ''), '0')::bigint AS male_count,
        coalesce(nullif(regexp_replace(raw_mo."femlNmprCnt", '[^0-9-]', '', 'g'), ''), '0')::bigint AS female_count,
        coalesce(nullif(regexp_replace(raw_mo."male0AgeNmprCnt", '[^0-9-]', '', 'g'), ''), '0')::bigint AS "male0AgeNmprCnt",
        coalesce(nullif(regexp_replace(raw_mo."male1AgeNmprCnt", '[^0-9-]', '', 'g'), ''), '0')::bigint AS "male1AgeNmprCnt",
        coalesce(nullif(regexp_replace(raw_mo."male2AgeNmprCnt", '[^0-9-]', '', 'g'), ''), '0')::bigint AS "male2AgeNmprCnt",
        coalesce(nullif(regexp_replace(raw_mo."male3AgeNmprCnt", '[^0-9-]', '', 'g'), ''), '0')::bigint AS "male3AgeNmprCnt",
        coalesce(nullif(regexp_replace(raw_mo."male4AgeNmprCnt", '[^0-9-]', '', 'g'), ''), '0')::bigint AS "male4AgeNmprCnt",
        coalesce(nullif(regexp_replace(raw_mo."male5AgeNmprCnt", '[^0-9-]', '', 'g'), ''), '0')::bigint AS "male5AgeNmprCnt",
        coalesce(nullif(regexp_replace(raw_mo."male6AgeNmprCnt", '[^0-9-]', '', 'g'), ''), '0')::bigint AS "male6AgeNmprCnt",
        coalesce(nullif(regexp_replace(raw_mo."male7AgeNmprCnt", '[^0-9-]', '', 'g'), ''), '0')::bigint AS "male7AgeNmprCnt",
        coalesce(nullif(regexp_replace(raw_mo."male8AgeNmprCnt", '[^0-9-]', '', 'g'), ''), '0')::bigint AS "male8AgeNmprCnt",
        coalesce(nullif(regexp_replace(raw_mo."male9AgeNmprCnt", '[^0-9-]', '', 'g'), ''), '0')::bigint AS "male9AgeNmprCnt",
        coalesce(nullif(regexp_replace(raw_mo."male10AgeNmprCnt", '[^0-9-]', '', 'g'), ''), '0')::bigint AS "male10AgeNmprCnt",
        coalesce(nullif(regexp_replace(raw_mo."male11AgeNmprCnt", '[^0-9-]', '', 'g'), ''), '0')::bigint AS "male11AgeNmprCnt",
        coalesce(nullif(regexp_replace(raw_mo."male12AgeNmprCnt", '[^0-9-]', '', 'g'), ''), '0')::bigint AS "male12AgeNmprCnt",
        coalesce(nullif(regexp_replace(raw_mo."male13AgeNmprCnt", '[^0-9-]', '', 'g'), ''), '0')::bigint AS "male13AgeNmprCnt",
        coalesce(nullif(regexp_replace(raw_mo."male14AgeNmprCnt", '[^0-9-]', '', 'g'), ''), '0')::bigint AS "male14AgeNmprCnt",
        coalesce(nullif(regexp_replace(raw_mo."male15AgeNmprCnt", '[^0-9-]', '', 'g'), ''), '0')::bigint AS "male15AgeNmprCnt",
        coalesce(nullif(regexp_replace(raw_mo."male16AgeNmprCnt", '[^0-9-]', '', 'g'), ''), '0')::bigint AS "male16AgeNmprCnt",
        coalesce(nullif(regexp_replace(raw_mo."male17AgeNmprCnt", '[^0-9-]', '', 'g'), ''), '0')::bigint AS "male17AgeNmprCnt",
        coalesce(nullif(regexp_replace(raw_mo."male18AgeNmprCnt", '[^0-9-]', '', 'g'), ''), '0')::bigint AS "male18AgeNmprCnt",
        coalesce(nullif(regexp_replace(raw_mo."male19AgeNmprCnt", '[^0-9-]', '', 'g'), ''), '0')::bigint AS "male19AgeNmprCnt",
        coalesce(nullif(regexp_replace(raw_mo."male20AgeNmprCnt", '[^0-9-]', '', 'g'), ''), '0')::bigint AS "male20AgeNmprCnt",
        coalesce(nullif(regexp_replace(raw_mo."male21AgeNmprCnt", '[^0-9-]', '', 'g'), ''), '0')::bigint AS "male21AgeNmprCnt",
        coalesce(nullif(regexp_replace(raw_mo."male22AgeNmprCnt", '[^0-9-]', '', 'g'), ''), '0')::bigint AS "male22AgeNmprCnt",
        coalesce(nullif(regexp_replace(raw_mo."male23AgeNmprCnt", '[^0-9-]', '', 'g'), ''), '0')::bigint AS "male23AgeNmprCnt",
        coalesce(nullif(regexp_replace(raw_mo."male24AgeNmprCnt", '[^0-9-]', '', 'g'), ''), '0')::bigint AS "male24AgeNmprCnt",
        coalesce(nullif(regexp_replace(raw_mo."male25AgeNmprCnt", '[^0-9-]', '', 'g'), ''), '0')::bigint AS "male25AgeNmprCnt",
        coalesce(nullif(regexp_replace(raw_mo."male26AgeNmprCnt", '[^0-9-]', '', 'g'), ''), '0')::bigint AS "male26AgeNmprCnt",
        coalesce(nullif(regexp_replace(raw_mo."male27AgeNmprCnt", '[^0-9-]', '', 'g'), ''), '0')::bigint AS "male27AgeNmprCnt",
        coalesce(nullif(regexp_replace(raw_mo."male28AgeNmprCnt", '[^0-9-]', '', 'g'), ''), '0')::bigint AS "male28AgeNmprCnt",
        coalesce(nullif(regexp_replace(raw_mo."male29AgeNmprCnt", '[^0-9-]', '', 'g'), ''), '0')::bigint AS "male29AgeNmprCnt",
        coalesce(nullif(regexp_replace(raw_mo."male30AgeNmprCnt", '[^0-9-]', '', 'g'), ''), '0')::bigint AS "male30AgeNmprCnt",
        coalesce(nullif(regexp_replace(raw_mo."male31AgeNmprCnt", '[^0-9-]', '', 'g'), ''), '0')::bigint AS "male31AgeNmprCnt",
        coalesce(nullif(regexp_replace(raw_mo."male32AgeNmprCnt", '[^0-9-]', '', 'g'), ''), '0')::bigint AS "male32AgeNmprCnt",
        coalesce(nullif(regexp_replace(raw_mo."male33AgeNmprCnt", '[^0-9-]', '', 'g'), ''), '0')::bigint AS "male33AgeNmprCnt",
        coalesce(nullif(regexp_replace(raw_mo."male34AgeNmprCnt", '[^0-9-]', '', 'g'), ''), '0')::bigint AS "male34AgeNmprCnt",
        coalesce(nullif(regexp_replace(raw_mo."male35AgeNmprCnt", '[^0-9-]', '', 'g'), ''), '0')::bigint AS "male35AgeNmprCnt",
        coalesce(nullif(regexp_replace(raw_mo."male36AgeNmprCnt", '[^0-9-]', '', 'g'), ''), '0')::bigint AS "male36AgeNmprCnt",
        coalesce(nullif(regexp_replace(raw_mo."male37AgeNmprCnt", '[^0-9-]', '', 'g'), ''), '0')::bigint AS "male37AgeNmprCnt",
        coalesce(nullif(regexp_replace(raw_mo."male38AgeNmprCnt", '[^0-9-]', '', 'g'), ''), '0')::bigint AS "male38AgeNmprCnt",
        coalesce(nullif(regexp_replace(raw_mo."male39AgeNmprCnt", '[^0-9-]', '', 'g'), ''), '0')::bigint AS "male39AgeNmprCnt",
        coalesce(nullif(regexp_replace(raw_mo."male40AgeNmprCnt", '[^0-9-]', '', 'g'), ''), '0')::bigint AS "male40AgeNmprCnt",
        coalesce(nullif(regexp_replace(raw_mo."male41AgeNmprCnt", '[^0-9-]', '', 'g'), ''), '0')::bigint AS "male41AgeNmprCnt",
        coalesce(nullif(regexp_replace(raw_mo."male42AgeNmprCnt", '[^0-9-]', '', 'g'), ''), '0')::bigint AS "male42AgeNmprCnt",
        coalesce(nullif(regexp_replace(raw_mo."male43AgeNmprCnt", '[^0-9-]', '', 'g'), ''), '0')::bigint AS "male43AgeNmprCnt",
        coalesce(nullif(regexp_replace(raw_mo."male44AgeNmprCnt", '[^0-9-]', '', 'g'), ''), '0')::bigint AS "male44AgeNmprCnt",
        coalesce(nullif(regexp_replace(raw_mo."male45AgeNmprCnt", '[^0-9-]', '', 'g'), ''), '0')::bigint AS "male45AgeNmprCnt",
        coalesce(nullif(regexp_replace(raw_mo."male46AgeNmprCnt", '[^0-9-]', '', 'g'), ''), '0')::bigint AS "male46AgeNmprCnt",
        coalesce(nullif(regexp_replace(raw_mo."male47AgeNmprCnt", '[^0-9-]', '', 'g'), ''), '0')::bigint AS "male47AgeNmprCnt",
        coalesce(nullif(regexp_replace(raw_mo."male48AgeNmprCnt", '[^0-9-]', '', 'g'), ''), '0')::bigint AS "male48AgeNmprCnt",
        coalesce(nullif(regexp_replace(raw_mo."male49AgeNmprCnt", '[^0-9-]', '', 'g'), ''), '0')::bigint AS "male49AgeNmprCnt",
        coalesce(nullif(regexp_replace(raw_mo."male50AgeNmprCnt", '[^0-9-]', '', 'g'), ''), '0')::bigint AS "male50AgeNmprCnt",
        coalesce(nullif(regexp_replace(raw_mo."male51AgeNmprCnt", '[^0-9-]', '', 'g'), ''), '0')::bigint AS "male51AgeNmprCnt",
        coalesce(nullif(regexp_replace(raw_mo."male52AgeNmprCnt", '[^0-9-]', '', 'g'), ''), '0')::bigint AS "male52AgeNmprCnt",
        coalesce(nullif(regexp_replace(raw_mo."male53AgeNmprCnt", '[^0-9-]', '', 'g'), ''), '0')::bigint AS "male53AgeNmprCnt",
        coalesce(nullif(regexp_replace(raw_mo."male54AgeNmprCnt", '[^0-9-]', '', 'g'), ''), '0')::bigint AS "male54AgeNmprCnt",
        coalesce(nullif(regexp_replace(raw_mo."male55AgeNmprCnt", '[^0-9-]', '', 'g'), ''), '0')::bigint AS "male55AgeNmprCnt",
        coalesce(nullif(regexp_replace(raw_mo."male56AgeNmprCnt", '[^0-9-]', '', 'g'), ''), '0')::bigint AS "male56AgeNmprCnt",
        coalesce(nullif(regexp_replace(raw_mo."male57AgeNmprCnt", '[^0-9-]', '', 'g'), ''), '0')::bigint AS "male57AgeNmprCnt",
        coalesce(nullif(regexp_replace(raw_mo."male58AgeNmprCnt", '[^0-9-]', '', 'g'), ''), '0')::bigint AS "male58AgeNmprCnt",
        coalesce(nullif(regexp_replace(raw_mo."male59AgeNmprCnt", '[^0-9-]', '', 'g'), ''), '0')::bigint AS "male59AgeNmprCnt",
        coalesce(nullif(regexp_replace(raw_mo."male60AgeNmprCnt", '[^0-9-]', '', 'g'), ''), '0')::bigint AS "male60AgeNmprCnt",
        coalesce(nullif(regexp_replace(raw_mo."male61AgeNmprCnt", '[^0-9-]', '', 'g'), ''), '0')::bigint AS "male61AgeNmprCnt",
        coalesce(nullif(regexp_replace(raw_mo."male62AgeNmprCnt", '[^0-9-]', '', 'g'), ''), '0')::bigint AS "male62AgeNmprCnt",
        coalesce(nullif(regexp_replace(raw_mo."male63AgeNmprCnt", '[^0-9-]', '', 'g'), ''), '0')::bigint AS "male63AgeNmprCnt",
        coalesce(nullif(regexp_replace(raw_mo."male64AgeNmprCnt", '[^0-9-]', '', 'g'), ''), '0')::bigint AS "male64AgeNmprCnt",
        coalesce(nullif(regexp_replace(raw_mo."male65AgeNmprCnt", '[^0-9-]', '', 'g'), ''), '0')::bigint AS "male65AgeNmprCnt",
        coalesce(nullif(regexp_replace(raw_mo."male66AgeNmprCnt", '[^0-9-]', '', 'g'), ''), '0')::bigint AS "male66AgeNmprCnt",
        coalesce(nullif(regexp_replace(raw_mo."male67AgeNmprCnt", '[^0-9-]', '', 'g'), ''), '0')::bigint AS "male67AgeNmprCnt",
        coalesce(nullif(regexp_replace(raw_mo."male68AgeNmprCnt", '[^0-9-]', '', 'g'), ''), '0')::bigint AS "male68AgeNmprCnt",
        coalesce(nullif(regexp_replace(raw_mo."male69AgeNmprCnt", '[^0-9-]', '', 'g'), ''), '0')::bigint AS "male69AgeNmprCnt",
        coalesce(nullif(regexp_replace(raw_mo."male70AgeNmprCnt", '[^0-9-]', '', 'g'), ''), '0')::bigint AS "male70AgeNmprCnt",
        coalesce(nullif(regexp_replace(raw_mo."male71AgeNmprCnt", '[^0-9-]', '', 'g'), ''), '0')::bigint AS "male71AgeNmprCnt",
        coalesce(nullif(regexp_replace(raw_mo."male72AgeNmprCnt", '[^0-9-]', '', 'g'), ''), '0')::bigint AS "male72AgeNmprCnt",
        coalesce(nullif(regexp_replace(raw_mo."male73AgeNmprCnt", '[^0-9-]', '', 'g'), ''), '0')::bigint AS "male73AgeNmprCnt",
        coalesce(nullif(regexp_replace(raw_mo."male74AgeNmprCnt", '[^0-9-]', '', 'g'), ''), '0')::bigint AS "male74AgeNmprCnt",
        coalesce(nullif(regexp_replace(raw_mo."male75AgeNmprCnt", '[^0-9-]', '', 'g'), ''), '0')::bigint AS "male75AgeNmprCnt",
        coalesce(nullif(regexp_replace(raw_mo."male76AgeNmprCnt", '[^0-9-]', '', 'g'), ''), '0')::bigint AS "male76AgeNmprCnt",
        coalesce(nullif(regexp_replace(raw_mo."male77AgeNmprCnt", '[^0-9-]', '', 'g'), ''), '0')::bigint AS "male77AgeNmprCnt",
        coalesce(nullif(regexp_replace(raw_mo."male78AgeNmprCnt", '[^0-9-]', '', 'g'), ''), '0')::bigint AS "male78AgeNmprCnt",
        coalesce(nullif(regexp_replace(raw_mo."male79AgeNmprCnt", '[^0-9-]', '', 'g'), ''), '0')::bigint AS "male79AgeNmprCnt",
        coalesce(nullif(regexp_replace(raw_mo."male80AgeNmprCnt", '[^0-9-]', '', 'g'), ''), '0')::bigint AS "male80AgeNmprCnt",
        coalesce(nullif(regexp_replace(raw_mo."male81AgeNmprCnt", '[^0-9-]', '', 'g'), ''), '0')::bigint AS "male81AgeNmprCnt",
        coalesce(nullif(regexp_replace(raw_mo."male82AgeNmprCnt", '[^0-9-]', '', 'g'), ''), '0')::bigint AS "male82AgeNmprCnt",
        coalesce(nullif(regexp_replace(raw_mo."male83AgeNmprCnt", '[^0-9-]', '', 'g'), ''), '0')::bigint AS "male83AgeNmprCnt",
        coalesce(nullif(regexp_replace(raw_mo."male84AgeNmprCnt", '[^0-9-]', '', 'g'), ''), '0')::bigint AS "male84AgeNmprCnt",
        coalesce(nullif(regexp_replace(raw_mo."male85AgeNmprCnt", '[^0-9-]', '', 'g'), ''), '0')::bigint AS "male85AgeNmprCnt",
        coalesce(nullif(regexp_replace(raw_mo."male86AgeNmprCnt", '[^0-9-]', '', 'g'), ''), '0')::bigint AS "male86AgeNmprCnt",
        coalesce(nullif(regexp_replace(raw_mo."male87AgeNmprCnt", '[^0-9-]', '', 'g'), ''), '0')::bigint AS "male87AgeNmprCnt",
        coalesce(nullif(regexp_replace(raw_mo."male88AgeNmprCnt", '[^0-9-]', '', 'g'), ''), '0')::bigint AS "male88AgeNmprCnt",
        coalesce(nullif(regexp_replace(raw_mo."male89AgeNmprCnt", '[^0-9-]', '', 'g'), ''), '0')::bigint AS "male89AgeNmprCnt",
        coalesce(nullif(regexp_replace(raw_mo."male90AgeNmprCnt", '[^0-9-]', '', 'g'), ''), '0')::bigint AS "male90AgeNmprCnt",
        coalesce(nullif(regexp_replace(raw_mo."male91AgeNmprCnt", '[^0-9-]', '', 'g'), ''), '0')::bigint AS "male91AgeNmprCnt",
        coalesce(nullif(regexp_replace(raw_mo."male92AgeNmprCnt", '[^0-9-]', '', 'g'), ''), '0')::bigint AS "male92AgeNmprCnt",
        coalesce(nullif(regexp_replace(raw_mo."male93AgeNmprCnt", '[^0-9-]', '', 'g'), ''), '0')::bigint AS "male93AgeNmprCnt",
        coalesce(nullif(regexp_replace(raw_mo."male94AgeNmprCnt", '[^0-9-]', '', 'g'), ''), '0')::bigint AS "male94AgeNmprCnt",
        coalesce(nullif(regexp_replace(raw_mo."male95AgeNmprCnt", '[^0-9-]', '', 'g'), ''), '0')::bigint AS "male95AgeNmprCnt",
        coalesce(nullif(regexp_replace(raw_mo."male96AgeNmprCnt", '[^0-9-]', '', 'g'), ''), '0')::bigint AS "male96AgeNmprCnt",
        coalesce(nullif(regexp_replace(raw_mo."male97AgeNmprCnt", '[^0-9-]', '', 'g'), ''), '0')::bigint AS "male97AgeNmprCnt",
        coalesce(nullif(regexp_replace(raw_mo."male98AgeNmprCnt", '[^0-9-]', '', 'g'), ''), '0')::bigint AS "male98AgeNmprCnt",
        coalesce(nullif(regexp_replace(raw_mo."male99AgeNmprCnt", '[^0-9-]', '', 'g'), ''), '0')::bigint AS "male99AgeNmprCnt",
        coalesce(nullif(regexp_replace(raw_mo."male100AgeNmprCnt", '[^0-9-]', '', 'g'), ''), '0')::bigint AS "male100AgeNmprCnt",
        coalesce(nullif(regexp_replace(raw_mo."male101AgeNmprCnt", '[^0-9-]', '', 'g'), ''), '0')::bigint AS "male101AgeNmprCnt",
        coalesce(nullif(regexp_replace(raw_mo."male102AgeNmprCnt", '[^0-9-]', '', 'g'), ''), '0')::bigint AS "male102AgeNmprCnt",
        coalesce(nullif(regexp_replace(raw_mo."male103AgeNmprCnt", '[^0-9-]', '', 'g'), ''), '0')::bigint AS "male103AgeNmprCnt",
        coalesce(nullif(regexp_replace(raw_mo."male104AgeNmprCnt", '[^0-9-]', '', 'g'), ''), '0')::bigint AS "male104AgeNmprCnt",
        coalesce(nullif(regexp_replace(raw_mo."male105AgeNmprCnt", '[^0-9-]', '', 'g'), ''), '0')::bigint AS "male105AgeNmprCnt",
        coalesce(nullif(regexp_replace(raw_mo."male106AgeNmprCnt", '[^0-9-]', '', 'g'), ''), '0')::bigint AS "male106AgeNmprCnt",
        coalesce(nullif(regexp_replace(raw_mo."male107AgeNmprCnt", '[^0-9-]', '', 'g'), ''), '0')::bigint AS "male107AgeNmprCnt",
        coalesce(nullif(regexp_replace(raw_mo."male108AgeNmprCnt", '[^0-9-]', '', 'g'), ''), '0')::bigint AS "male108AgeNmprCnt",
        coalesce(nullif(regexp_replace(raw_mo."male109AgeNmprCnt", '[^0-9-]', '', 'g'), ''), '0')::bigint AS "male109AgeNmprCnt",
        coalesce(nullif(regexp_replace(raw_mo."male110AgeNmprCnt", '[^0-9-]', '', 'g'), ''), '0')::bigint AS "male110AgeNmprCnt",
        coalesce(nullif(regexp_replace(raw_mo."feml0AgeNmprCnt", '[^0-9-]', '', 'g'), ''), '0')::bigint AS "feml0AgeNmprCnt",
        coalesce(nullif(regexp_replace(raw_mo."feml1AgeNmprCnt", '[^0-9-]', '', 'g'), ''), '0')::bigint AS "feml1AgeNmprCnt",
        coalesce(nullif(regexp_replace(raw_mo."feml2AgeNmprCnt", '[^0-9-]', '', 'g'), ''), '0')::bigint AS "feml2AgeNmprCnt",
        coalesce(nullif(regexp_replace(raw_mo."feml3AgeNmprCnt", '[^0-9-]', '', 'g'), ''), '0')::bigint AS "feml3AgeNmprCnt",
        coalesce(nullif(regexp_replace(raw_mo."feml4AgeNmprCnt", '[^0-9-]', '', 'g'), ''), '0')::bigint AS "feml4AgeNmprCnt",
        coalesce(nullif(regexp_replace(raw_mo."feml5AgeNmprCnt", '[^0-9-]', '', 'g'), ''), '0')::bigint AS "feml5AgeNmprCnt",
        coalesce(nullif(regexp_replace(raw_mo."feml6AgeNmprCnt", '[^0-9-]', '', 'g'), ''), '0')::bigint AS "feml6AgeNmprCnt",
        coalesce(nullif(regexp_replace(raw_mo."feml7AgeNmprCnt", '[^0-9-]', '', 'g'), ''), '0')::bigint AS "feml7AgeNmprCnt",
        coalesce(nullif(regexp_replace(raw_mo."feml8AgeNmprCnt", '[^0-9-]', '', 'g'), ''), '0')::bigint AS "feml8AgeNmprCnt",
        coalesce(nullif(regexp_replace(raw_mo."feml9AgeNmprCnt", '[^0-9-]', '', 'g'), ''), '0')::bigint AS "feml9AgeNmprCnt",
        coalesce(nullif(regexp_replace(raw_mo."feml10AgeNmprCnt", '[^0-9-]', '', 'g'), ''), '0')::bigint AS "feml10AgeNmprCnt",
        coalesce(nullif(regexp_replace(raw_mo."feml11AgeNmprCnt", '[^0-9-]', '', 'g'), ''), '0')::bigint AS "feml11AgeNmprCnt",
        coalesce(nullif(regexp_replace(raw_mo."feml12AgeNmprCnt", '[^0-9-]', '', 'g'), ''), '0')::bigint AS "feml12AgeNmprCnt",
        coalesce(nullif(regexp_replace(raw_mo."feml13AgeNmprCnt", '[^0-9-]', '', 'g'), ''), '0')::bigint AS "feml13AgeNmprCnt",
        coalesce(nullif(regexp_replace(raw_mo."feml14AgeNmprCnt", '[^0-9-]', '', 'g'), ''), '0')::bigint AS "feml14AgeNmprCnt",
        coalesce(nullif(regexp_replace(raw_mo."feml15AgeNmprCnt", '[^0-9-]', '', 'g'), ''), '0')::bigint AS "feml15AgeNmprCnt",
        coalesce(nullif(regexp_replace(raw_mo."feml16AgeNmprCnt", '[^0-9-]', '', 'g'), ''), '0')::bigint AS "feml16AgeNmprCnt",
        coalesce(nullif(regexp_replace(raw_mo."feml17AgeNmprCnt", '[^0-9-]', '', 'g'), ''), '0')::bigint AS "feml17AgeNmprCnt",
        coalesce(nullif(regexp_replace(raw_mo."feml18AgeNmprCnt", '[^0-9-]', '', 'g'), ''), '0')::bigint AS "feml18AgeNmprCnt",
        coalesce(nullif(regexp_replace(raw_mo."feml19AgeNmprCnt", '[^0-9-]', '', 'g'), ''), '0')::bigint AS "feml19AgeNmprCnt",
        coalesce(nullif(regexp_replace(raw_mo."feml20AgeNmprCnt", '[^0-9-]', '', 'g'), ''), '0')::bigint AS "feml20AgeNmprCnt",
        coalesce(nullif(regexp_replace(raw_mo."feml21AgeNmprCnt", '[^0-9-]', '', 'g'), ''), '0')::bigint AS "feml21AgeNmprCnt",
        coalesce(nullif(regexp_replace(raw_mo."feml22AgeNmprCnt", '[^0-9-]', '', 'g'), ''), '0')::bigint AS "feml22AgeNmprCnt",
        coalesce(nullif(regexp_replace(raw_mo."feml23AgeNmprCnt", '[^0-9-]', '', 'g'), ''), '0')::bigint AS "feml23AgeNmprCnt",
        coalesce(nullif(regexp_replace(raw_mo."feml24AgeNmprCnt", '[^0-9-]', '', 'g'), ''), '0')::bigint AS "feml24AgeNmprCnt",
        coalesce(nullif(regexp_replace(raw_mo."feml25AgeNmprCnt", '[^0-9-]', '', 'g'), ''), '0')::bigint AS "feml25AgeNmprCnt",
        coalesce(nullif(regexp_replace(raw_mo."feml26AgeNmprCnt", '[^0-9-]', '', 'g'), ''), '0')::bigint AS "feml26AgeNmprCnt",
        coalesce(nullif(regexp_replace(raw_mo."feml27AgeNmprCnt", '[^0-9-]', '', 'g'), ''), '0')::bigint AS "feml27AgeNmprCnt",
        coalesce(nullif(regexp_replace(raw_mo."feml28AgeNmprCnt", '[^0-9-]', '', 'g'), ''), '0')::bigint AS "feml28AgeNmprCnt",
        coalesce(nullif(regexp_replace(raw_mo."feml29AgeNmprCnt", '[^0-9-]', '', 'g'), ''), '0')::bigint AS "feml29AgeNmprCnt",
        coalesce(nullif(regexp_replace(raw_mo."feml30AgeNmprCnt", '[^0-9-]', '', 'g'), ''), '0')::bigint AS "feml30AgeNmprCnt",
        coalesce(nullif(regexp_replace(raw_mo."feml31AgeNmprCnt", '[^0-9-]', '', 'g'), ''), '0')::bigint AS "feml31AgeNmprCnt",
        coalesce(nullif(regexp_replace(raw_mo."feml32AgeNmprCnt", '[^0-9-]', '', 'g'), ''), '0')::bigint AS "feml32AgeNmprCnt",
        coalesce(nullif(regexp_replace(raw_mo."feml33AgeNmprCnt", '[^0-9-]', '', 'g'), ''), '0')::bigint AS "feml33AgeNmprCnt",
        coalesce(nullif(regexp_replace(raw_mo."feml34AgeNmprCnt", '[^0-9-]', '', 'g'), ''), '0')::bigint AS "feml34AgeNmprCnt",
        coalesce(nullif(regexp_replace(raw_mo."feml35AgeNmprCnt", '[^0-9-]', '', 'g'), ''), '0')::bigint AS "feml35AgeNmprCnt",
        coalesce(nullif(regexp_replace(raw_mo."feml36AgeNmprCnt", '[^0-9-]', '', 'g'), ''), '0')::bigint AS "feml36AgeNmprCnt",
        coalesce(nullif(regexp_replace(raw_mo."feml37AgeNmprCnt", '[^0-9-]', '', 'g'), ''), '0')::bigint AS "feml37AgeNmprCnt",
        coalesce(nullif(regexp_replace(raw_mo."feml38AgeNmprCnt", '[^0-9-]', '', 'g'), ''), '0')::bigint AS "feml38AgeNmprCnt",
        coalesce(nullif(regexp_replace(raw_mo."feml39AgeNmprCnt", '[^0-9-]', '', 'g'), ''), '0')::bigint AS "feml39AgeNmprCnt",
        coalesce(nullif(regexp_replace(raw_mo."feml40AgeNmprCnt", '[^0-9-]', '', 'g'), ''), '0')::bigint AS "feml40AgeNmprCnt",
        coalesce(nullif(regexp_replace(raw_mo."feml41AgeNmprCnt", '[^0-9-]', '', 'g'), ''), '0')::bigint AS "feml41AgeNmprCnt",
        coalesce(nullif(regexp_replace(raw_mo."feml42AgeNmprCnt", '[^0-9-]', '', 'g'), ''), '0')::bigint AS "feml42AgeNmprCnt",
        coalesce(nullif(regexp_replace(raw_mo."feml43AgeNmprCnt", '[^0-9-]', '', 'g'), ''), '0')::bigint AS "feml43AgeNmprCnt",
        coalesce(nullif(regexp_replace(raw_mo."feml44AgeNmprCnt", '[^0-9-]', '', 'g'), ''), '0')::bigint AS "feml44AgeNmprCnt",
        coalesce(nullif(regexp_replace(raw_mo."feml45AgeNmprCnt", '[^0-9-]', '', 'g'), ''), '0')::bigint AS "feml45AgeNmprCnt",
        coalesce(nullif(regexp_replace(raw_mo."feml46AgeNmprCnt", '[^0-9-]', '', 'g'), ''), '0')::bigint AS "feml46AgeNmprCnt",
        coalesce(nullif(regexp_replace(raw_mo."feml47AgeNmprCnt", '[^0-9-]', '', 'g'), ''), '0')::bigint AS "feml47AgeNmprCnt",
        coalesce(nullif(regexp_replace(raw_mo."feml48AgeNmprCnt", '[^0-9-]', '', 'g'), ''), '0')::bigint AS "feml48AgeNmprCnt",
        coalesce(nullif(regexp_replace(raw_mo."feml49AgeNmprCnt", '[^0-9-]', '', 'g'), ''), '0')::bigint AS "feml49AgeNmprCnt",
        coalesce(nullif(regexp_replace(raw_mo."feml50AgeNmprCnt", '[^0-9-]', '', 'g'), ''), '0')::bigint AS "feml50AgeNmprCnt",
        coalesce(nullif(regexp_replace(raw_mo."feml51AgeNmprCnt", '[^0-9-]', '', 'g'), ''), '0')::bigint AS "feml51AgeNmprCnt",
        coalesce(nullif(regexp_replace(raw_mo."feml52AgeNmprCnt", '[^0-9-]', '', 'g'), ''), '0')::bigint AS "feml52AgeNmprCnt",
        coalesce(nullif(regexp_replace(raw_mo."feml53AgeNmprCnt", '[^0-9-]', '', 'g'), ''), '0')::bigint AS "feml53AgeNmprCnt",
        coalesce(nullif(regexp_replace(raw_mo."feml54AgeNmprCnt", '[^0-9-]', '', 'g'), ''), '0')::bigint AS "feml54AgeNmprCnt",
        coalesce(nullif(regexp_replace(raw_mo."feml55AgeNmprCnt", '[^0-9-]', '', 'g'), ''), '0')::bigint AS "feml55AgeNmprCnt",
        coalesce(nullif(regexp_replace(raw_mo."feml56AgeNmprCnt", '[^0-9-]', '', 'g'), ''), '0')::bigint AS "feml56AgeNmprCnt",
        coalesce(nullif(regexp_replace(raw_mo."feml57AgeNmprCnt", '[^0-9-]', '', 'g'), ''), '0')::bigint AS "feml57AgeNmprCnt",
        coalesce(nullif(regexp_replace(raw_mo."feml58AgeNmprCnt", '[^0-9-]', '', 'g'), ''), '0')::bigint AS "feml58AgeNmprCnt",
        coalesce(nullif(regexp_replace(raw_mo."feml59AgeNmprCnt", '[^0-9-]', '', 'g'), ''), '0')::bigint AS "feml59AgeNmprCnt",
        coalesce(nullif(regexp_replace(raw_mo."feml60AgeNmprCnt", '[^0-9-]', '', 'g'), ''), '0')::bigint AS "feml60AgeNmprCnt",
        coalesce(nullif(regexp_replace(raw_mo."feml61AgeNmprCnt", '[^0-9-]', '', 'g'), ''), '0')::bigint AS "feml61AgeNmprCnt",
        coalesce(nullif(regexp_replace(raw_mo."feml62AgeNmprCnt", '[^0-9-]', '', 'g'), ''), '0')::bigint AS "feml62AgeNmprCnt",
        coalesce(nullif(regexp_replace(raw_mo."feml63AgeNmprCnt", '[^0-9-]', '', 'g'), ''), '0')::bigint AS "feml63AgeNmprCnt",
        coalesce(nullif(regexp_replace(raw_mo."feml64AgeNmprCnt", '[^0-9-]', '', 'g'), ''), '0')::bigint AS "feml64AgeNmprCnt",
        coalesce(nullif(regexp_replace(raw_mo."feml65AgeNmprCnt", '[^0-9-]', '', 'g'), ''), '0')::bigint AS "feml65AgeNmprCnt",
        coalesce(nullif(regexp_replace(raw_mo."feml66AgeNmprCnt", '[^0-9-]', '', 'g'), ''), '0')::bigint AS "feml66AgeNmprCnt",
        coalesce(nullif(regexp_replace(raw_mo."feml67AgeNmprCnt", '[^0-9-]', '', 'g'), ''), '0')::bigint AS "feml67AgeNmprCnt",
        coalesce(nullif(regexp_replace(raw_mo."feml68AgeNmprCnt", '[^0-9-]', '', 'g'), ''), '0')::bigint AS "feml68AgeNmprCnt",
        coalesce(nullif(regexp_replace(raw_mo."feml69AgeNmprCnt", '[^0-9-]', '', 'g'), ''), '0')::bigint AS "feml69AgeNmprCnt",
        coalesce(nullif(regexp_replace(raw_mo."feml70AgeNmprCnt", '[^0-9-]', '', 'g'), ''), '0')::bigint AS "feml70AgeNmprCnt",
        coalesce(nullif(regexp_replace(raw_mo."feml71AgeNmprCnt", '[^0-9-]', '', 'g'), ''), '0')::bigint AS "feml71AgeNmprCnt",
        coalesce(nullif(regexp_replace(raw_mo."feml72AgeNmprCnt", '[^0-9-]', '', 'g'), ''), '0')::bigint AS "feml72AgeNmprCnt",
        coalesce(nullif(regexp_replace(raw_mo."feml73AgeNmprCnt", '[^0-9-]', '', 'g'), ''), '0')::bigint AS "feml73AgeNmprCnt",
        coalesce(nullif(regexp_replace(raw_mo."feml74AgeNmprCnt", '[^0-9-]', '', 'g'), ''), '0')::bigint AS "feml74AgeNmprCnt",
        coalesce(nullif(regexp_replace(raw_mo."feml75AgeNmprCnt", '[^0-9-]', '', 'g'), ''), '0')::bigint AS "feml75AgeNmprCnt",
        coalesce(nullif(regexp_replace(raw_mo."feml76AgeNmprCnt", '[^0-9-]', '', 'g'), ''), '0')::bigint AS "feml76AgeNmprCnt",
        coalesce(nullif(regexp_replace(raw_mo."feml77AgeNmprCnt", '[^0-9-]', '', 'g'), ''), '0')::bigint AS "feml77AgeNmprCnt",
        coalesce(nullif(regexp_replace(raw_mo."feml78AgeNmprCnt", '[^0-9-]', '', 'g'), ''), '0')::bigint AS "feml78AgeNmprCnt",
        coalesce(nullif(regexp_replace(raw_mo."feml79AgeNmprCnt", '[^0-9-]', '', 'g'), ''), '0')::bigint AS "feml79AgeNmprCnt",
        coalesce(nullif(regexp_replace(raw_mo."feml80AgeNmprCnt", '[^0-9-]', '', 'g'), ''), '0')::bigint AS "feml80AgeNmprCnt",
        coalesce(nullif(regexp_replace(raw_mo."feml81AgeNmprCnt", '[^0-9-]', '', 'g'), ''), '0')::bigint AS "feml81AgeNmprCnt",
        coalesce(nullif(regexp_replace(raw_mo."feml82AgeNmprCnt", '[^0-9-]', '', 'g'), ''), '0')::bigint AS "feml82AgeNmprCnt",
        coalesce(nullif(regexp_replace(raw_mo."feml83AgeNmprCnt", '[^0-9-]', '', 'g'), ''), '0')::bigint AS "feml83AgeNmprCnt",
        coalesce(nullif(regexp_replace(raw_mo."feml84AgeNmprCnt", '[^0-9-]', '', 'g'), ''), '0')::bigint AS "feml84AgeNmprCnt",
        coalesce(nullif(regexp_replace(raw_mo."feml85AgeNmprCnt", '[^0-9-]', '', 'g'), ''), '0')::bigint AS "feml85AgeNmprCnt",
        coalesce(nullif(regexp_replace(raw_mo."feml86AgeNmprCnt", '[^0-9-]', '', 'g'), ''), '0')::bigint AS "feml86AgeNmprCnt",
        coalesce(nullif(regexp_replace(raw_mo."feml87AgeNmprCnt", '[^0-9-]', '', 'g'), ''), '0')::bigint AS "feml87AgeNmprCnt",
        coalesce(nullif(regexp_replace(raw_mo."feml88AgeNmprCnt", '[^0-9-]', '', 'g'), ''), '0')::bigint AS "feml88AgeNmprCnt",
        coalesce(nullif(regexp_replace(raw_mo."feml89AgeNmprCnt", '[^0-9-]', '', 'g'), ''), '0')::bigint AS "feml89AgeNmprCnt",
        coalesce(nullif(regexp_replace(raw_mo."feml90AgeNmprCnt", '[^0-9-]', '', 'g'), ''), '0')::bigint AS "feml90AgeNmprCnt",
        coalesce(nullif(regexp_replace(raw_mo."feml91AgeNmprCnt", '[^0-9-]', '', 'g'), ''), '0')::bigint AS "feml91AgeNmprCnt",
        coalesce(nullif(regexp_replace(raw_mo."feml92AgeNmprCnt", '[^0-9-]', '', 'g'), ''), '0')::bigint AS "feml92AgeNmprCnt",
        coalesce(nullif(regexp_replace(raw_mo."feml93AgeNmprCnt", '[^0-9-]', '', 'g'), ''), '0')::bigint AS "feml93AgeNmprCnt",
        coalesce(nullif(regexp_replace(raw_mo."feml94AgeNmprCnt", '[^0-9-]', '', 'g'), ''), '0')::bigint AS "feml94AgeNmprCnt",
        coalesce(nullif(regexp_replace(raw_mo."feml95AgeNmprCnt", '[^0-9-]', '', 'g'), ''), '0')::bigint AS "feml95AgeNmprCnt",
        coalesce(nullif(regexp_replace(raw_mo."feml96AgeNmprCnt", '[^0-9-]', '', 'g'), ''), '0')::bigint AS "feml96AgeNmprCnt",
        coalesce(nullif(regexp_replace(raw_mo."feml97AgeNmprCnt", '[^0-9-]', '', 'g'), ''), '0')::bigint AS "feml97AgeNmprCnt",
        coalesce(nullif(regexp_replace(raw_mo."feml98AgeNmprCnt", '[^0-9-]', '', 'g'), ''), '0')::bigint AS "feml98AgeNmprCnt",
        coalesce(nullif(regexp_replace(raw_mo."feml99AgeNmprCnt", '[^0-9-]', '', 'g'), ''), '0')::bigint AS "feml99AgeNmprCnt",
        coalesce(nullif(regexp_replace(raw_mo."feml100AgeNmprCnt", '[^0-9-]', '', 'g'), ''), '0')::bigint AS "feml100AgeNmprCnt",
        coalesce(nullif(regexp_replace(raw_mo."feml101AgeNmprCnt", '[^0-9-]', '', 'g'), ''), '0')::bigint AS "feml101AgeNmprCnt",
        coalesce(nullif(regexp_replace(raw_mo."feml102AgeNmprCnt", '[^0-9-]', '', 'g'), ''), '0')::bigint AS "feml102AgeNmprCnt",
        coalesce(nullif(regexp_replace(raw_mo."feml103AgeNmprCnt", '[^0-9-]', '', 'g'), ''), '0')::bigint AS "feml103AgeNmprCnt",
        coalesce(nullif(regexp_replace(raw_mo."feml104AgeNmprCnt", '[^0-9-]', '', 'g'), ''), '0')::bigint AS "feml104AgeNmprCnt",
        coalesce(nullif(regexp_replace(raw_mo."feml105AgeNmprCnt", '[^0-9-]', '', 'g'), ''), '0')::bigint AS "feml105AgeNmprCnt",
        coalesce(nullif(regexp_replace(raw_mo."feml106AgeNmprCnt", '[^0-9-]', '', 'g'), ''), '0')::bigint AS "feml106AgeNmprCnt",
        coalesce(nullif(regexp_replace(raw_mo."feml107AgeNmprCnt", '[^0-9-]', '', 'g'), ''), '0')::bigint AS "feml107AgeNmprCnt",
        coalesce(nullif(regexp_replace(raw_mo."feml108AgeNmprCnt", '[^0-9-]', '', 'g'), ''), '0')::bigint AS "feml108AgeNmprCnt",
        coalesce(nullif(regexp_replace(raw_mo."feml109AgeNmprCnt", '[^0-9-]', '', 'g'), ''), '0')::bigint AS "feml109AgeNmprCnt",
        coalesce(nullif(regexp_replace(raw_mo."feml110AgeNmprCnt", '[^0-9-]', '', 'g'), ''), '0')::bigint AS "feml110AgeNmprCnt"
    FROM raw.migration_od AS raw_mo
    JOIN clean_migration_od_missing_dates AS md
      ON raw_mo."statsYm" = md.date::text
),
standardized_names AS (
    SELECT
        p.*,
        ds.region_sido AS destination_sido,
        os.region_sido AS origin_sido,
        CASE
            WHEN ds.region_sido = '세종'
                THEN '세종시'
            WHEN ds.region_sido = '인천'
                 AND p.destination_sigungu_raw = '영종구'
                THEN '중구'
            WHEN ds.region_sido = '인천'
                 AND p.destination_sigungu_raw = '제물포구'
                THEN '동구'
            WHEN ds.region_sido = '인천'
                 AND p.destination_sigungu_raw = '서해구'
                THEN '서구'
            WHEN ds.region_sido = '인천'
                 AND p.destination_sigungu_raw = '검단구'
                THEN '서구'
            WHEN p.destination_sigungu_raw LIKE '%시 %구'
                THEN split_part(p.destination_sigungu_raw, ' ', 1)
            WHEN p.destination_sigungu_raw = '창원시(통합)'
                THEN '창원시'
            ELSE p.destination_sigungu_raw
        END AS destination_sigungu,
        CASE
            WHEN os.region_sido = '세종'
                THEN '세종시'
            WHEN os.region_sido = '인천'
                 AND p.origin_sigungu_raw = '영종구'
                THEN '중구'
            WHEN os.region_sido = '인천'
                 AND p.origin_sigungu_raw = '제물포구'
                THEN '동구'
            WHEN os.region_sido = '인천'
                 AND p.origin_sigungu_raw = '서해구'
                THEN '서구'
            WHEN os.region_sido = '인천'
                 AND p.origin_sigungu_raw = '검단구'
                THEN '서구'
            WHEN p.origin_sigungu_raw LIKE '%시 %구'
                THEN split_part(p.origin_sigungu_raw, ' ', 1)
            WHEN p.origin_sigungu_raw = '창원시(통합)'
                THEN '창원시'
            ELSE p.origin_sigungu_raw
        END AS origin_sigungu
    FROM prepared AS p
    LEFT JOIN sido_by_name AS ds
      ON p.destination_sido_raw = ds.raw_sido
    LEFT JOIN sido_by_name AS os
      ON p.origin_sido_raw = os.raw_sido
)
SELECT *
FROM standardized_names;

CREATE TEMP TABLE migration_od_unmapped_regions ON COMMIT DROP AS
SELECT
    'destination' AS side,
    destination_code AS raw_code,
    destination_sido_raw AS raw_sido,
    destination_sigungu_raw AS raw_sigungu,
    destination_sido AS region_sido,
    destination_sigungu AS region_sigungu,
    count(*) AS row_count
FROM migration_od_standardized AS st
LEFT JOIN region_merge_key AS rk
  ON st.destination_sido = rk.region_sido
 AND st.destination_sigungu = rk.region_sigungu
WHERE rk.region_sido IS NULL
GROUP BY
    destination_code,
    destination_sido_raw,
    destination_sigungu_raw,
    destination_sido,
    destination_sigungu
UNION ALL
SELECT
    'origin' AS side,
    origin_code AS raw_code,
    origin_sido_raw AS raw_sido,
    origin_sigungu_raw AS raw_sigungu,
    origin_sido AS region_sido,
    origin_sigungu AS region_sigungu,
    count(*) AS row_count
FROM migration_od_standardized AS st
LEFT JOIN region_merge_key AS rk
  ON st.origin_sido = rk.region_sido
 AND st.origin_sigungu = rk.region_sigungu
WHERE rk.region_sido IS NULL
GROUP BY
    origin_code,
    origin_sido_raw,
    origin_sigungu_raw,
    origin_sido,
    origin_sigungu;

CREATE TEMP TABLE migration_od_unmapped_guard (
    side text NOT NULL,
    raw_code text,
    raw_sido text,
    raw_sigungu text,
    region_sido text,
    region_sigungu text,
    row_count bigint,
    CONSTRAINT no_unmapped_migration_od_region CHECK (false)
) ON COMMIT DROP;

INSERT INTO migration_od_unmapped_guard (
    side,
    raw_code,
    raw_sido,
    raw_sigungu,
    region_sido,
    region_sigungu,
    row_count
)
SELECT
    side,
    raw_code,
    raw_sido,
    raw_sigungu,
    region_sido,
    region_sigungu,
    row_count
FROM migration_od_unmapped_regions;

CREATE TEMP TABLE migration_od_canonical ON COMMIT DROP AS
SELECT
    st.date,
    dest.region_sido AS destination_sido,
    dest.region_sigungu AS destination_sigungu,
    org.region_sido AS origin_sido,
    org.region_sigungu AS origin_sigungu,
    SUM(st.total_count)::bigint AS total_count,
    SUM(st.male_count)::bigint AS male_count,
    SUM(st.female_count)::bigint AS female_count,
    (SUM(st."male0AgeNmprCnt") + SUM(st."male1AgeNmprCnt") + SUM(st."male2AgeNmprCnt") + SUM(st."male3AgeNmprCnt") + SUM(st."male4AgeNmprCnt"))::bigint AS "male_0_4",
    (SUM(st."male5AgeNmprCnt") + SUM(st."male6AgeNmprCnt") + SUM(st."male7AgeNmprCnt") + SUM(st."male8AgeNmprCnt") + SUM(st."male9AgeNmprCnt"))::bigint AS "male_5_9",
    (SUM(st."male10AgeNmprCnt") + SUM(st."male11AgeNmprCnt") + SUM(st."male12AgeNmprCnt") + SUM(st."male13AgeNmprCnt") + SUM(st."male14AgeNmprCnt"))::bigint AS "male_10_14",
    (SUM(st."male15AgeNmprCnt") + SUM(st."male16AgeNmprCnt") + SUM(st."male17AgeNmprCnt") + SUM(st."male18AgeNmprCnt") + SUM(st."male19AgeNmprCnt"))::bigint AS "male_15_19",
    (SUM(st."male20AgeNmprCnt") + SUM(st."male21AgeNmprCnt") + SUM(st."male22AgeNmprCnt") + SUM(st."male23AgeNmprCnt") + SUM(st."male24AgeNmprCnt"))::bigint AS "male_20_24",
    (SUM(st."male25AgeNmprCnt") + SUM(st."male26AgeNmprCnt") + SUM(st."male27AgeNmprCnt") + SUM(st."male28AgeNmprCnt") + SUM(st."male29AgeNmprCnt"))::bigint AS "male_25_29",
    (SUM(st."male30AgeNmprCnt") + SUM(st."male31AgeNmprCnt") + SUM(st."male32AgeNmprCnt") + SUM(st."male33AgeNmprCnt") + SUM(st."male34AgeNmprCnt"))::bigint AS "male_30_34",
    (SUM(st."male35AgeNmprCnt") + SUM(st."male36AgeNmprCnt") + SUM(st."male37AgeNmprCnt") + SUM(st."male38AgeNmprCnt") + SUM(st."male39AgeNmprCnt"))::bigint AS "male_35_39",
    (SUM(st."male40AgeNmprCnt") + SUM(st."male41AgeNmprCnt") + SUM(st."male42AgeNmprCnt") + SUM(st."male43AgeNmprCnt") + SUM(st."male44AgeNmprCnt"))::bigint AS "male_40_44",
    (SUM(st."male45AgeNmprCnt") + SUM(st."male46AgeNmprCnt") + SUM(st."male47AgeNmprCnt") + SUM(st."male48AgeNmprCnt") + SUM(st."male49AgeNmprCnt"))::bigint AS "male_45_49",
    (SUM(st."male50AgeNmprCnt") + SUM(st."male51AgeNmprCnt") + SUM(st."male52AgeNmprCnt") + SUM(st."male53AgeNmprCnt") + SUM(st."male54AgeNmprCnt"))::bigint AS "male_50_54",
    (SUM(st."male55AgeNmprCnt") + SUM(st."male56AgeNmprCnt") + SUM(st."male57AgeNmprCnt") + SUM(st."male58AgeNmprCnt") + SUM(st."male59AgeNmprCnt"))::bigint AS "male_55_59",
    (SUM(st."male60AgeNmprCnt") + SUM(st."male61AgeNmprCnt") + SUM(st."male62AgeNmprCnt") + SUM(st."male63AgeNmprCnt") + SUM(st."male64AgeNmprCnt"))::bigint AS "male_60_64",
    (SUM(st."male65AgeNmprCnt") + SUM(st."male66AgeNmprCnt") + SUM(st."male67AgeNmprCnt") + SUM(st."male68AgeNmprCnt") + SUM(st."male69AgeNmprCnt"))::bigint AS "male_65_69",
    (SUM(st."male70AgeNmprCnt") + SUM(st."male71AgeNmprCnt") + SUM(st."male72AgeNmprCnt") + SUM(st."male73AgeNmprCnt") + SUM(st."male74AgeNmprCnt"))::bigint AS "male_70_74",
    (SUM(st."male75AgeNmprCnt") + SUM(st."male76AgeNmprCnt") + SUM(st."male77AgeNmprCnt") + SUM(st."male78AgeNmprCnt") + SUM(st."male79AgeNmprCnt"))::bigint AS "male_75_79",
    (SUM(st."male80AgeNmprCnt") + SUM(st."male81AgeNmprCnt") + SUM(st."male82AgeNmprCnt") + SUM(st."male83AgeNmprCnt") + SUM(st."male84AgeNmprCnt") + SUM(st."male85AgeNmprCnt") + SUM(st."male86AgeNmprCnt") + SUM(st."male87AgeNmprCnt") + SUM(st."male88AgeNmprCnt") + SUM(st."male89AgeNmprCnt") + SUM(st."male90AgeNmprCnt") + SUM(st."male91AgeNmprCnt") + SUM(st."male92AgeNmprCnt") + SUM(st."male93AgeNmprCnt") + SUM(st."male94AgeNmprCnt") + SUM(st."male95AgeNmprCnt") + SUM(st."male96AgeNmprCnt") + SUM(st."male97AgeNmprCnt") + SUM(st."male98AgeNmprCnt") + SUM(st."male99AgeNmprCnt") + SUM(st."male100AgeNmprCnt") + SUM(st."male101AgeNmprCnt") + SUM(st."male102AgeNmprCnt") + SUM(st."male103AgeNmprCnt") + SUM(st."male104AgeNmprCnt") + SUM(st."male105AgeNmprCnt") + SUM(st."male106AgeNmprCnt") + SUM(st."male107AgeNmprCnt") + SUM(st."male108AgeNmprCnt") + SUM(st."male109AgeNmprCnt") + SUM(st."male110AgeNmprCnt"))::bigint AS "male_80_plus",
    (SUM(st."feml0AgeNmprCnt") + SUM(st."feml1AgeNmprCnt") + SUM(st."feml2AgeNmprCnt") + SUM(st."feml3AgeNmprCnt") + SUM(st."feml4AgeNmprCnt"))::bigint AS "female_0_4",
    (SUM(st."feml5AgeNmprCnt") + SUM(st."feml6AgeNmprCnt") + SUM(st."feml7AgeNmprCnt") + SUM(st."feml8AgeNmprCnt") + SUM(st."feml9AgeNmprCnt"))::bigint AS "female_5_9",
    (SUM(st."feml10AgeNmprCnt") + SUM(st."feml11AgeNmprCnt") + SUM(st."feml12AgeNmprCnt") + SUM(st."feml13AgeNmprCnt") + SUM(st."feml14AgeNmprCnt"))::bigint AS "female_10_14",
    (SUM(st."feml15AgeNmprCnt") + SUM(st."feml16AgeNmprCnt") + SUM(st."feml17AgeNmprCnt") + SUM(st."feml18AgeNmprCnt") + SUM(st."feml19AgeNmprCnt"))::bigint AS "female_15_19",
    (SUM(st."feml20AgeNmprCnt") + SUM(st."feml21AgeNmprCnt") + SUM(st."feml22AgeNmprCnt") + SUM(st."feml23AgeNmprCnt") + SUM(st."feml24AgeNmprCnt"))::bigint AS "female_20_24",
    (SUM(st."feml25AgeNmprCnt") + SUM(st."feml26AgeNmprCnt") + SUM(st."feml27AgeNmprCnt") + SUM(st."feml28AgeNmprCnt") + SUM(st."feml29AgeNmprCnt"))::bigint AS "female_25_29",
    (SUM(st."feml30AgeNmprCnt") + SUM(st."feml31AgeNmprCnt") + SUM(st."feml32AgeNmprCnt") + SUM(st."feml33AgeNmprCnt") + SUM(st."feml34AgeNmprCnt"))::bigint AS "female_30_34",
    (SUM(st."feml35AgeNmprCnt") + SUM(st."feml36AgeNmprCnt") + SUM(st."feml37AgeNmprCnt") + SUM(st."feml38AgeNmprCnt") + SUM(st."feml39AgeNmprCnt"))::bigint AS "female_35_39",
    (SUM(st."feml40AgeNmprCnt") + SUM(st."feml41AgeNmprCnt") + SUM(st."feml42AgeNmprCnt") + SUM(st."feml43AgeNmprCnt") + SUM(st."feml44AgeNmprCnt"))::bigint AS "female_40_44",
    (SUM(st."feml45AgeNmprCnt") + SUM(st."feml46AgeNmprCnt") + SUM(st."feml47AgeNmprCnt") + SUM(st."feml48AgeNmprCnt") + SUM(st."feml49AgeNmprCnt"))::bigint AS "female_45_49",
    (SUM(st."feml50AgeNmprCnt") + SUM(st."feml51AgeNmprCnt") + SUM(st."feml52AgeNmprCnt") + SUM(st."feml53AgeNmprCnt") + SUM(st."feml54AgeNmprCnt"))::bigint AS "female_50_54",
    (SUM(st."feml55AgeNmprCnt") + SUM(st."feml56AgeNmprCnt") + SUM(st."feml57AgeNmprCnt") + SUM(st."feml58AgeNmprCnt") + SUM(st."feml59AgeNmprCnt"))::bigint AS "female_55_59",
    (SUM(st."feml60AgeNmprCnt") + SUM(st."feml61AgeNmprCnt") + SUM(st."feml62AgeNmprCnt") + SUM(st."feml63AgeNmprCnt") + SUM(st."feml64AgeNmprCnt"))::bigint AS "female_60_64",
    (SUM(st."feml65AgeNmprCnt") + SUM(st."feml66AgeNmprCnt") + SUM(st."feml67AgeNmprCnt") + SUM(st."feml68AgeNmprCnt") + SUM(st."feml69AgeNmprCnt"))::bigint AS "female_65_69",
    (SUM(st."feml70AgeNmprCnt") + SUM(st."feml71AgeNmprCnt") + SUM(st."feml72AgeNmprCnt") + SUM(st."feml73AgeNmprCnt") + SUM(st."feml74AgeNmprCnt"))::bigint AS "female_70_74",
    (SUM(st."feml75AgeNmprCnt") + SUM(st."feml76AgeNmprCnt") + SUM(st."feml77AgeNmprCnt") + SUM(st."feml78AgeNmprCnt") + SUM(st."feml79AgeNmprCnt"))::bigint AS "female_75_79",
    (SUM(st."feml80AgeNmprCnt") + SUM(st."feml81AgeNmprCnt") + SUM(st."feml82AgeNmprCnt") + SUM(st."feml83AgeNmprCnt") + SUM(st."feml84AgeNmprCnt") + SUM(st."feml85AgeNmprCnt") + SUM(st."feml86AgeNmprCnt") + SUM(st."feml87AgeNmprCnt") + SUM(st."feml88AgeNmprCnt") + SUM(st."feml89AgeNmprCnt") + SUM(st."feml90AgeNmprCnt") + SUM(st."feml91AgeNmprCnt") + SUM(st."feml92AgeNmprCnt") + SUM(st."feml93AgeNmprCnt") + SUM(st."feml94AgeNmprCnt") + SUM(st."feml95AgeNmprCnt") + SUM(st."feml96AgeNmprCnt") + SUM(st."feml97AgeNmprCnt") + SUM(st."feml98AgeNmprCnt") + SUM(st."feml99AgeNmprCnt") + SUM(st."feml100AgeNmprCnt") + SUM(st."feml101AgeNmprCnt") + SUM(st."feml102AgeNmprCnt") + SUM(st."feml103AgeNmprCnt") + SUM(st."feml104AgeNmprCnt") + SUM(st."feml105AgeNmprCnt") + SUM(st."feml106AgeNmprCnt") + SUM(st."feml107AgeNmprCnt") + SUM(st."feml108AgeNmprCnt") + SUM(st."feml109AgeNmprCnt") + SUM(st."feml110AgeNmprCnt"))::bigint AS "female_80_plus"
FROM migration_od_standardized AS st
JOIN region_merge_key AS dest
  ON st.destination_sido = dest.region_sido
 AND st.destination_sigungu = dest.region_sigungu
JOIN region_merge_key AS org
  ON st.origin_sido = org.region_sido
 AND st.origin_sigungu = org.region_sigungu
WHERE NOT (
    dest.region_sido = org.region_sido
    AND dest.region_sigungu = org.region_sigungu
)
GROUP BY
    st.date,
    dest.region_sido,
    dest.region_sigungu,
    org.region_sido,
    org.region_sigungu;

CREATE TEMP TABLE migration_od_dimension_base ON COMMIT DROP AS
SELECT
    date,
    destination_sido,
    destination_sigungu,
    origin_sido,
    origin_sigungu,
    'all'::text AS sex,
    'all'::text AS age,
    total_count AS move_count
FROM migration_od_canonical
UNION ALL
SELECT
    date,
    destination_sido,
    destination_sigungu,
    origin_sido,
    origin_sigungu,
    'male'::text AS sex,
    'all'::text AS age,
    male_count AS move_count
FROM migration_od_canonical
UNION ALL
SELECT
    date,
    destination_sido,
    destination_sigungu,
    origin_sido,
    origin_sigungu,
    'female'::text AS sex,
    'all'::text AS age,
    female_count AS move_count
FROM migration_od_canonical
UNION ALL
SELECT
    date,
    destination_sido,
    destination_sigungu,
    origin_sido,
    origin_sigungu,
    'all'::text AS sex,
    '0-4'::text AS age,
    ("male_0_4" + "female_0_4")::bigint AS move_count
FROM migration_od_canonical
UNION ALL
SELECT
    date,
    destination_sido,
    destination_sigungu,
    origin_sido,
    origin_sigungu,
    'all'::text AS sex,
    '5-9'::text AS age,
    ("male_5_9" + "female_5_9")::bigint AS move_count
FROM migration_od_canonical
UNION ALL
SELECT
    date,
    destination_sido,
    destination_sigungu,
    origin_sido,
    origin_sigungu,
    'all'::text AS sex,
    '10-14'::text AS age,
    ("male_10_14" + "female_10_14")::bigint AS move_count
FROM migration_od_canonical
UNION ALL
SELECT
    date,
    destination_sido,
    destination_sigungu,
    origin_sido,
    origin_sigungu,
    'all'::text AS sex,
    '15-19'::text AS age,
    ("male_15_19" + "female_15_19")::bigint AS move_count
FROM migration_od_canonical
UNION ALL
SELECT
    date,
    destination_sido,
    destination_sigungu,
    origin_sido,
    origin_sigungu,
    'all'::text AS sex,
    '20-24'::text AS age,
    ("male_20_24" + "female_20_24")::bigint AS move_count
FROM migration_od_canonical
UNION ALL
SELECT
    date,
    destination_sido,
    destination_sigungu,
    origin_sido,
    origin_sigungu,
    'all'::text AS sex,
    '25-29'::text AS age,
    ("male_25_29" + "female_25_29")::bigint AS move_count
FROM migration_od_canonical
UNION ALL
SELECT
    date,
    destination_sido,
    destination_sigungu,
    origin_sido,
    origin_sigungu,
    'all'::text AS sex,
    '30-34'::text AS age,
    ("male_30_34" + "female_30_34")::bigint AS move_count
FROM migration_od_canonical
UNION ALL
SELECT
    date,
    destination_sido,
    destination_sigungu,
    origin_sido,
    origin_sigungu,
    'all'::text AS sex,
    '35-39'::text AS age,
    ("male_35_39" + "female_35_39")::bigint AS move_count
FROM migration_od_canonical
UNION ALL
SELECT
    date,
    destination_sido,
    destination_sigungu,
    origin_sido,
    origin_sigungu,
    'all'::text AS sex,
    '40-44'::text AS age,
    ("male_40_44" + "female_40_44")::bigint AS move_count
FROM migration_od_canonical
UNION ALL
SELECT
    date,
    destination_sido,
    destination_sigungu,
    origin_sido,
    origin_sigungu,
    'all'::text AS sex,
    '45-49'::text AS age,
    ("male_45_49" + "female_45_49")::bigint AS move_count
FROM migration_od_canonical
UNION ALL
SELECT
    date,
    destination_sido,
    destination_sigungu,
    origin_sido,
    origin_sigungu,
    'all'::text AS sex,
    '50-54'::text AS age,
    ("male_50_54" + "female_50_54")::bigint AS move_count
FROM migration_od_canonical
UNION ALL
SELECT
    date,
    destination_sido,
    destination_sigungu,
    origin_sido,
    origin_sigungu,
    'all'::text AS sex,
    '55-59'::text AS age,
    ("male_55_59" + "female_55_59")::bigint AS move_count
FROM migration_od_canonical
UNION ALL
SELECT
    date,
    destination_sido,
    destination_sigungu,
    origin_sido,
    origin_sigungu,
    'all'::text AS sex,
    '60-64'::text AS age,
    ("male_60_64" + "female_60_64")::bigint AS move_count
FROM migration_od_canonical
UNION ALL
SELECT
    date,
    destination_sido,
    destination_sigungu,
    origin_sido,
    origin_sigungu,
    'all'::text AS sex,
    '65-69'::text AS age,
    ("male_65_69" + "female_65_69")::bigint AS move_count
FROM migration_od_canonical
UNION ALL
SELECT
    date,
    destination_sido,
    destination_sigungu,
    origin_sido,
    origin_sigungu,
    'all'::text AS sex,
    '70-74'::text AS age,
    ("male_70_74" + "female_70_74")::bigint AS move_count
FROM migration_od_canonical
UNION ALL
SELECT
    date,
    destination_sido,
    destination_sigungu,
    origin_sido,
    origin_sigungu,
    'all'::text AS sex,
    '75-79'::text AS age,
    ("male_75_79" + "female_75_79")::bigint AS move_count
FROM migration_od_canonical
UNION ALL
SELECT
    date,
    destination_sido,
    destination_sigungu,
    origin_sido,
    origin_sigungu,
    'all'::text AS sex,
    '80-'::text AS age,
    ("male_80_plus" + "female_80_plus")::bigint AS move_count
FROM migration_od_canonical
UNION ALL
SELECT
    date,
    destination_sido,
    destination_sigungu,
    origin_sido,
    origin_sigungu,
    'male'::text AS sex,
    '0-4'::text AS age,
    "male_0_4" AS move_count
FROM migration_od_canonical
UNION ALL
SELECT
    date,
    destination_sido,
    destination_sigungu,
    origin_sido,
    origin_sigungu,
    'male'::text AS sex,
    '5-9'::text AS age,
    "male_5_9" AS move_count
FROM migration_od_canonical
UNION ALL
SELECT
    date,
    destination_sido,
    destination_sigungu,
    origin_sido,
    origin_sigungu,
    'male'::text AS sex,
    '10-14'::text AS age,
    "male_10_14" AS move_count
FROM migration_od_canonical
UNION ALL
SELECT
    date,
    destination_sido,
    destination_sigungu,
    origin_sido,
    origin_sigungu,
    'male'::text AS sex,
    '15-19'::text AS age,
    "male_15_19" AS move_count
FROM migration_od_canonical
UNION ALL
SELECT
    date,
    destination_sido,
    destination_sigungu,
    origin_sido,
    origin_sigungu,
    'male'::text AS sex,
    '20-24'::text AS age,
    "male_20_24" AS move_count
FROM migration_od_canonical
UNION ALL
SELECT
    date,
    destination_sido,
    destination_sigungu,
    origin_sido,
    origin_sigungu,
    'male'::text AS sex,
    '25-29'::text AS age,
    "male_25_29" AS move_count
FROM migration_od_canonical
UNION ALL
SELECT
    date,
    destination_sido,
    destination_sigungu,
    origin_sido,
    origin_sigungu,
    'male'::text AS sex,
    '30-34'::text AS age,
    "male_30_34" AS move_count
FROM migration_od_canonical
UNION ALL
SELECT
    date,
    destination_sido,
    destination_sigungu,
    origin_sido,
    origin_sigungu,
    'male'::text AS sex,
    '35-39'::text AS age,
    "male_35_39" AS move_count
FROM migration_od_canonical
UNION ALL
SELECT
    date,
    destination_sido,
    destination_sigungu,
    origin_sido,
    origin_sigungu,
    'male'::text AS sex,
    '40-44'::text AS age,
    "male_40_44" AS move_count
FROM migration_od_canonical
UNION ALL
SELECT
    date,
    destination_sido,
    destination_sigungu,
    origin_sido,
    origin_sigungu,
    'male'::text AS sex,
    '45-49'::text AS age,
    "male_45_49" AS move_count
FROM migration_od_canonical
UNION ALL
SELECT
    date,
    destination_sido,
    destination_sigungu,
    origin_sido,
    origin_sigungu,
    'male'::text AS sex,
    '50-54'::text AS age,
    "male_50_54" AS move_count
FROM migration_od_canonical
UNION ALL
SELECT
    date,
    destination_sido,
    destination_sigungu,
    origin_sido,
    origin_sigungu,
    'male'::text AS sex,
    '55-59'::text AS age,
    "male_55_59" AS move_count
FROM migration_od_canonical
UNION ALL
SELECT
    date,
    destination_sido,
    destination_sigungu,
    origin_sido,
    origin_sigungu,
    'male'::text AS sex,
    '60-64'::text AS age,
    "male_60_64" AS move_count
FROM migration_od_canonical
UNION ALL
SELECT
    date,
    destination_sido,
    destination_sigungu,
    origin_sido,
    origin_sigungu,
    'male'::text AS sex,
    '65-69'::text AS age,
    "male_65_69" AS move_count
FROM migration_od_canonical
UNION ALL
SELECT
    date,
    destination_sido,
    destination_sigungu,
    origin_sido,
    origin_sigungu,
    'male'::text AS sex,
    '70-74'::text AS age,
    "male_70_74" AS move_count
FROM migration_od_canonical
UNION ALL
SELECT
    date,
    destination_sido,
    destination_sigungu,
    origin_sido,
    origin_sigungu,
    'male'::text AS sex,
    '75-79'::text AS age,
    "male_75_79" AS move_count
FROM migration_od_canonical
UNION ALL
SELECT
    date,
    destination_sido,
    destination_sigungu,
    origin_sido,
    origin_sigungu,
    'male'::text AS sex,
    '80-'::text AS age,
    "male_80_plus" AS move_count
FROM migration_od_canonical
UNION ALL
SELECT
    date,
    destination_sido,
    destination_sigungu,
    origin_sido,
    origin_sigungu,
    'female'::text AS sex,
    '0-4'::text AS age,
    "female_0_4" AS move_count
FROM migration_od_canonical
UNION ALL
SELECT
    date,
    destination_sido,
    destination_sigungu,
    origin_sido,
    origin_sigungu,
    'female'::text AS sex,
    '5-9'::text AS age,
    "female_5_9" AS move_count
FROM migration_od_canonical
UNION ALL
SELECT
    date,
    destination_sido,
    destination_sigungu,
    origin_sido,
    origin_sigungu,
    'female'::text AS sex,
    '10-14'::text AS age,
    "female_10_14" AS move_count
FROM migration_od_canonical
UNION ALL
SELECT
    date,
    destination_sido,
    destination_sigungu,
    origin_sido,
    origin_sigungu,
    'female'::text AS sex,
    '15-19'::text AS age,
    "female_15_19" AS move_count
FROM migration_od_canonical
UNION ALL
SELECT
    date,
    destination_sido,
    destination_sigungu,
    origin_sido,
    origin_sigungu,
    'female'::text AS sex,
    '20-24'::text AS age,
    "female_20_24" AS move_count
FROM migration_od_canonical
UNION ALL
SELECT
    date,
    destination_sido,
    destination_sigungu,
    origin_sido,
    origin_sigungu,
    'female'::text AS sex,
    '25-29'::text AS age,
    "female_25_29" AS move_count
FROM migration_od_canonical
UNION ALL
SELECT
    date,
    destination_sido,
    destination_sigungu,
    origin_sido,
    origin_sigungu,
    'female'::text AS sex,
    '30-34'::text AS age,
    "female_30_34" AS move_count
FROM migration_od_canonical
UNION ALL
SELECT
    date,
    destination_sido,
    destination_sigungu,
    origin_sido,
    origin_sigungu,
    'female'::text AS sex,
    '35-39'::text AS age,
    "female_35_39" AS move_count
FROM migration_od_canonical
UNION ALL
SELECT
    date,
    destination_sido,
    destination_sigungu,
    origin_sido,
    origin_sigungu,
    'female'::text AS sex,
    '40-44'::text AS age,
    "female_40_44" AS move_count
FROM migration_od_canonical
UNION ALL
SELECT
    date,
    destination_sido,
    destination_sigungu,
    origin_sido,
    origin_sigungu,
    'female'::text AS sex,
    '45-49'::text AS age,
    "female_45_49" AS move_count
FROM migration_od_canonical
UNION ALL
SELECT
    date,
    destination_sido,
    destination_sigungu,
    origin_sido,
    origin_sigungu,
    'female'::text AS sex,
    '50-54'::text AS age,
    "female_50_54" AS move_count
FROM migration_od_canonical
UNION ALL
SELECT
    date,
    destination_sido,
    destination_sigungu,
    origin_sido,
    origin_sigungu,
    'female'::text AS sex,
    '55-59'::text AS age,
    "female_55_59" AS move_count
FROM migration_od_canonical
UNION ALL
SELECT
    date,
    destination_sido,
    destination_sigungu,
    origin_sido,
    origin_sigungu,
    'female'::text AS sex,
    '60-64'::text AS age,
    "female_60_64" AS move_count
FROM migration_od_canonical
UNION ALL
SELECT
    date,
    destination_sido,
    destination_sigungu,
    origin_sido,
    origin_sigungu,
    'female'::text AS sex,
    '65-69'::text AS age,
    "female_65_69" AS move_count
FROM migration_od_canonical
UNION ALL
SELECT
    date,
    destination_sido,
    destination_sigungu,
    origin_sido,
    origin_sigungu,
    'female'::text AS sex,
    '70-74'::text AS age,
    "female_70_74" AS move_count
FROM migration_od_canonical
UNION ALL
SELECT
    date,
    destination_sido,
    destination_sigungu,
    origin_sido,
    origin_sigungu,
    'female'::text AS sex,
    '75-79'::text AS age,
    "female_75_79" AS move_count
FROM migration_od_canonical
UNION ALL
SELECT
    date,
    destination_sido,
    destination_sigungu,
    origin_sido,
    origin_sigungu,
    'female'::text AS sex,
    '80-'::text AS age,
    "female_80_plus" AS move_count
FROM migration_od_canonical;

INSERT INTO clean.clean_inflow (
    date,
    region_sido,
    region_sigungu,
    from_sido,
    from_sigungu,
    inflow
)
SELECT
    date,
    destination_sido,
    destination_sigungu,
    origin_sido,
    origin_sigungu,
    move_count
FROM migration_od_dimension_base
WHERE sex = 'all'
  AND age = 'all'
  AND move_count > 0;

INSERT INTO clean.clean_inflow_sex (
    date,
    region_sido,
    region_sigungu,
    from_sido,
    from_sigungu,
    sex,
    inflow
)
SELECT
    date,
    destination_sido,
    destination_sigungu,
    origin_sido,
    origin_sigungu,
    sex,
    move_count
FROM migration_od_dimension_base
WHERE age = 'all'
  AND move_count > 0;

INSERT INTO clean.clean_inflow_age (
    date,
    region_sido,
    region_sigungu,
    from_sido,
    from_sigungu,
    age,
    inflow
)
SELECT
    date,
    destination_sido,
    destination_sigungu,
    origin_sido,
    origin_sigungu,
    age,
    move_count
FROM migration_od_dimension_base
WHERE sex = 'all'
  AND move_count > 0;

INSERT INTO clean.clean_inflow_sex_age (
    date,
    region_sido,
    region_sigungu,
    from_sido,
    from_sigungu,
    sex,
    age,
    inflow
)
SELECT
    date,
    destination_sido,
    destination_sigungu,
    origin_sido,
    origin_sigungu,
    sex,
    age,
    move_count
FROM migration_od_dimension_base
WHERE move_count > 0;

INSERT INTO clean.clean_outflow (
    date,
    region_sido,
    region_sigungu,
    to_sido,
    to_sigungu,
    outflow
)
SELECT
    date,
    origin_sido,
    origin_sigungu,
    destination_sido,
    destination_sigungu,
    move_count
FROM migration_od_dimension_base
WHERE sex = 'all'
  AND age = 'all'
  AND move_count > 0;

INSERT INTO clean.clean_outflow_sex (
    date,
    region_sido,
    region_sigungu,
    to_sido,
    to_sigungu,
    sex,
    outflow
)
SELECT
    date,
    origin_sido,
    origin_sigungu,
    destination_sido,
    destination_sigungu,
    sex,
    move_count
FROM migration_od_dimension_base
WHERE age = 'all'
  AND move_count > 0;

INSERT INTO clean.clean_outflow_age (
    date,
    region_sido,
    region_sigungu,
    to_sido,
    to_sigungu,
    age,
    outflow
)
SELECT
    date,
    origin_sido,
    origin_sigungu,
    destination_sido,
    destination_sigungu,
    age,
    move_count
FROM migration_od_dimension_base
WHERE sex = 'all'
  AND move_count > 0;

INSERT INTO clean.clean_outflow_sex_age (
    date,
    region_sido,
    region_sigungu,
    to_sido,
    to_sigungu,
    sex,
    age,
    outflow
)
SELECT
    date,
    origin_sido,
    origin_sigungu,
    destination_sido,
    destination_sigungu,
    sex,
    age,
    move_count
FROM migration_od_dimension_base
WHERE move_count > 0;

COMMIT;
